<html>
    <head>
    </head>
    <body style="padding:8px;text-align:left;background-color:#ffffff;font-family:Verdana, Arial, Helvetica, sans-serif;font-size:9px;font-style:normal;line-height:14px;font-weight:normal;font-variant:normal;color:#333333;">
        <h3>Lead Generated by <?php echo $name; ?></h3>
        <br/>
        <h5>Information</h5>
        <p>
            Name: <?php echo $c['Client']['first_name'].' '.$c['Client']['last_name']; ?><br/>
            Email: <a href="<?php echo $c['Client']['email']; ?>"><?php echo $c['Client']['email']; ?></a><br/>
            Phone: <?php echo $c['Client']['phone']; ?><br/>
            Wedding Date: <?php echo date('m-j-Y',strtotime($c['Client']['wedding_date'])); ?><br/>
            Zip Code: <?php echo $c['Client']['zip'];?><br/>
            <?php echo $rr; ?>
        </p>
        
        <hr/>
        <p style="font-size:80%;">
        </p>
        
    </body>
</html>