<html>
    <head>
    </head>
    <body style="padding:8px;text-align:left;background-color:#ffffff;font-family:Verdana, Arial, Helvetica, sans-serif;font-size:9px;font-style:normal;line-height:14px;font-weight:normal;font-variant:normal;color:#333333;">
        <h3>New Lead Generated by <?php echo $name; ?></h3>
        <br/>
        <h5>Information</h5>
        <p>
        
            <?php foreach ($fields as $f) {
                                                   echo $f['Field']['display_name'].': ';
								switch ($f['Field']['type']) {
									case 'date':
										echo date('m-j-Y',strtotime($u['Client'][$f['Field']['name']]));
										break;
									case 'datetime':
										echo date('g:ia m-j-Y',strtotime($u['Client'][$f['Field']['name']]));
										break;
									case 'tinyint':
										if (isset($u['Client'][$f['Field']['name']])&&$u['Client'][$f['Field']['name']]=='1') {
											echo 'yes';
										} else {
											echo 'no';
										}
										break;
									default:
										if ($f['Field']['name']!='email') {
											echo $u['Client'][$f['Field']['name']];	
										} else {
											echo '<a href="mailto:'.$u['Client'][$f['Field']['name']].'">'.$u['Client'][$f['Field']['name']].'</a>';	
										}
										break;
								}
                                                                echo '<br/>';

            } ?>
            
            <?php echo $rr; ?>
        </p>
        
        <hr/>
        <p style="font-size:80%;">
        </p>
        
    </body>
</html>